config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myswapapp.urls', namespace='myswapapp'))
]
    
if settings.DEBUG:
    #import debug_toolbar
    #urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myswapapp/urls.py
from django.http import HttpResponse
from django.urls import path
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from .models import Product, User, Order, Chat, Messages, Profile, OrderProduct, Address, Basket
from .forms import LoginForm
from . import views
from .views import CheckoutView, HomeView, products, login, View, ProductDetailView,  PaymentView, swapper_profile, createOrder, updateOrder, deleteOrder, swapperPage, welcome, registerPage, profileSettings, logout, orderConfirmation, CheckoutView, add_product_in_basket
from django.utils import timezone
from django.urls import reverse_lazy

app_name= 'myswapapp'

urlpatterns = [
    
    path('', HomeView.as_view(), name = 'home'),
    path('products/', views.products, name= 'products'), 
    path('swapper_profile/', views.swapper_profile, name= 'swapper_profile'),
    path('login/', views.login, name= 'login'),
    path('logout/', views.logout, name= 'logout'),
    path('product_detail/<slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('order_summary/', CheckoutView.as_view(), name='order_summary'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('create_order/<str:pk>/', views.createOrder, name='create_order'),
    path('updateOrder/<str:pk>/', views.updateOrder, name='update_order'),
    path('deleteOrder/<str:pk>/', views.deleteOrder, name='delete_order'),
    path('swapper_homepage/', views.swapperPage, name='swapper_homepage'),
    path('welcome/', views.welcome, name='welcome'),
    path('register/', views.registerPage, name='register'),
    path('profile/', views.profileSettings, name='profile'),
    path('order_confirmation/', views.orderConfirmation, name='order_confirmation'),
    #path('order_summary/', OrderSummaryView.as_view(), name='order_summary'),
    path('add_product_in_basket/', views.add_product_in_basket, name='add_product_in_basket')


    

    
]

myswapapp/models.py
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.utils import timezone
from datetime import datetime
from django.shortcuts import reverse
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse_lazy






class User(models.Model):

    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)#CASCADE=when ever a user is deleted it will delete the reationship with the other
    name = models.CharField(max_length=200, null=True)
    phone= models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    #profile = models.ForeignKey(Profile, null=True, on_delete=models.CASCADE)

    
    

    def __str__(self):
        return self.user.username

class Chat(models.Model):
    users = models.ManyToManyField(User)
    name = models.CharField(max_length=200)
    slug= models.SlugField(null=True)
    
class Messages(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    text =models.CharField(max_length=500)
    date_sent = models.DateTimeField(auto_now_add=True, null=True)



ADDRESS_CHOICES =(
    ('B', 'Billing'),
    ('S', 'Shipping')
)




class Product(models.Model):
    CATEGORY = (
            ('Indoor Decorations', 'Indoor Decorations'),
            ('Outdoor Decorations', 'Outdoor Decoration'),
    )

    title = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=200, null=True)
    location = models.CharField(max_length=200, null=True)
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    slug= models.SlugField(null=True)
    price = models.DecimalField(max_digits=7, decimal_places= 2)
    image = models.ImageField(default='default.jpg', upload_to='static/images')
    
    def __str__(self):
        return str(self.id)
    
    class Meta:
        verbose_name_plural = "Products"



    def get_absolute_url(self):
        return reverse('myswapapp:product_detail', kwargs={ 'slug': self.slug})

    def get_basket_url(self):
        return reverse('myswappapp:basket', kwargs={'slug': self.slug})
    
    def get_add_product_in_basket_url(self):
        return reverse('myswapapp:add_product_in_basket', kwargs={'slug': self.slug})

    def get_remove_product_from_basket_url(self):
        return reverse('myswapapp:remove_product_from_basket', kwargs={'slug': self.slug})

    def get_remove_single_product_from_basket_url(self):
        return reverse('myswapapp:remove_single_product_from_basket',kwargs={'slug': self.slug})


class OrderProduct(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    
    def get_total_product_price(self):
        return self.quantity * self.product.price

    def __str__(self):
        return f"{self.quantity} of {self.product.title}"

    


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    products = models.ManyToManyField(OrderProduct)
    start_date = models.DateTimeField(auto_now_add=True)
    
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    id = models.AutoField(primary_key=True)

    

    def __str__(self):
        return self.user.username
 
    def get_total_product_price(self):
        return self.product.price

    
        



class Profile(models.Model):
    user = models.CharField(max_length=200, null=True)
    Uid=models.AutoField(primary_key=True)
    location = models.CharField(max_length=100, null=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pic')
    slug= models.SlugField(null=True)

   
    def __str__(self):
        return f'{self.user} Profile'

    def get_absolute_url(self):
        return reverse('myswapapp: profile_swapper.html', kwargs={ 'slug': self.slug})
    
    def save(self):
        super().save()

        img= Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)




class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    street_address = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=50)
    address_type = models.CharField(max_length=1, choices= ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username 


class Basket(models.Model):
    user =models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

myswapapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.forms import inlineformset_factory
from django.contrib import admin
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate, logout
from django.http import JsonResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.contrib import messages
from .models import Product, User, Order, Chat, Messages, Profile, OrderProduct, Address, Basket
from django.views.generic import ListView, DetailView, View, CreateView, UpdateView
from .forms import PaymentForm, ProfilePageForm, OrderForm, CreateUserForm, RegistrationForm, PasswordChangeForm, PasswordResetForm, LoginForm, UserForm
from django.utils import timezone
from django.urls import reverse_lazy

from . import views





def welcome(request):
    return render(request,'myswapapp/welcome.html')


class HomeView(ListView):
    model = Product
    template_name = 'myswapapp/home.html'



def login(request):

	if request.method == 'POST':
		username = request.POST.get('username')
		password =request.POST.get('password')

		user = authenticate(request, username=username, password=password)

		if user is not None:
			login(request)
			return redirect('home')
		else:
			messages.info(request, 'Username OR password is incorrect')

	context = {}
	return render(request, 'myswapapp/login.html', context)



def registerPage(request):

	form = CreateUserForm()
	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')

			group = Group.objects.get(name='user')
			user.groups.add(group)
			
			User.objects.create(
				user=user,
				name=user.username,
				)

			messages.success(request, 'Account was created for ' + username)

			return redirect('myswapapp/login.html')
		
	context = {'form':form}
	return render(request, 'myswapapp/register.html', context)    
   



def products(request):
        products: Product.objects.all()
        return render(request, "myswapapp/home.html", {'products': products})



class ProductDetailView(View):
    def get(self, request, slug):
        product =Product.objects.get(slug=slug)
        return render(request, 'myswapapp/product_detail.html',{'product': product})





    
def swapper_profile(request, pk):
    
    user =User.objects.get(id=pk)
    
    context ={'user':user }
    return render(request, 'myswapapp/swapper_profile.html', context)



def swapperPage(request):
    
	orders = request.user.user.order_set.all()

	total_orders = orders.count()
	
	print('ORDERS:', orders)

	context = {'orders':orders, 'total_orders':total_orders}
	return render(request, 'myswapapp/swapper.html', context)




def profileSettings(request):
	user = request.user
	form = UserForm(instance=user)

	if request.method == 'POST':
		form = UserForm(request.POST, request.FILES,instance=user)
		if form.is_valid():
			form.save()

	context = {'form':form}
	return render(request, 'myswapapp/profile_settings.html', context)





def add_product_in_basket(request):
    user=request.user
    product_id = request.GET.get('prod_id')
    product =Product.objects.get(id=product_id)
    Basket(user=user, product=product).save()
    return redirect('myswapapp/add_product_in_basket.html')



def show_basket(request):
    if request.user.is_authenticated:
        user = request.user
        basket = Basket.objects.filter(user=user)
        amount = 0.0
        total_amount = 0.0
        basket_product = [p for p in Basket.objects.all() if p.user == user]
        #print(basket_product)
        if products in basket_product:
            total =(products.quantity * products.product.price)
            totalamount = total.order
        return render(request, 'myswapapp/add_product_in_basket.html', {'basket':basket, 'totalamount':totalamount})
        



def basket(request):
    if request.user.is_authenticated:
        user = request.user.user
        order, created = Order.objects.get_or_create(
            user= request.user, 
            ordered=False, 
            product=product)
        products = order.orderproduct_set.all()
    else:
        products =[]
        order = {'get_basket_total':0, 'get_basket_products':0}

    context = {'products':products, 'order': order}
    return render(request, 'myswapapp/basket.html', context)








def createOrder(request, pk):
    user = User.objects.get(id=pk)
    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    context = {'form': form}
    return render(request, 'myswapapp/order_form.html', context)



def updateOrder(request, pk):
    order =Order.objects.get(id=pk)
    form = OrderForm(instance=order)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {"form": form}
    return render(request, 'myswapapp/order_form.html', context) 



def deleteOrder(request, pk):
    order =Order.objects.get(id-pk)
    if request.method == 'POST':
        order.delete()
        return redirect('/')

    context = {'product': order}
    return render(request, 'myswapapp/delete_order.html', context)


#class OrderSummaryView(View):
 #   def get(self, *args, **kwargs):

  #      try:
   #         order = Order.objects.get(user=self.request.user, ordered=False)
    #        context = {
     #           'order': order
      #      }
       #     return render(self.request, 'myswapapp/order_summary.html', context)
       # except ObjectDoesNotExist:
        #    messages.success(self.request, "You dont have an active order")
         #   return redirect('myswapapp/home.html')



class CheckoutView(View):
   def get(self, *args, **kwargs):
        form = PaymentForm()
        context = {
            'form': form
        }
        return render(self.request, "myswapapp/order_summary.html", context)
        
        def post(self, *args, **kwargs):
            form = PaymentForm(self.request.POST or None)
            try:
                order = Order.objects.get(user=self.request.user, ordered=False)
                if form.is_valid():
                    street_address = form.cleaned_data.get('street_address')
                    state = form.cleaned_data.get('state')
                    zipcode = form.cleaned_data.get('zipcode')
                    
                    payment_option = form.cleaned_data.get('payment_option')
                    billing_address = Address(
                        user=self.request.user,
                        street_address = street_address,
                        state = state,
                        zipcode = zipcode,
                        address_type = 'B')

                    
                    billing_address.save()
                    order.billing_address = billing_address
                    order.save()
                                    
                    return redirect('myswapapp/order_summary.html')
                messages.warning(self.request, "Failed Checkout")
                return redirect('myswapapp/order_summary.html')
            except ObjectDoesNotExist:
                messages.error(self.request, "You do not have an active order")
                return redirect("myswapapp/home.html")

def updateProduct(request):
    return JsonResponse("This product was added to your Swapp order", safe=False)               

            

class PaymentView(View):
    def get(self, *args, **kwargs):
        form = PaymentForm()
        context = {
            'form' : form
        }

        return render(self.request, 'myswapapp/payment.html', context)

    def post(self, *args, **kwargs):
        form = PaymentForm(self.request.POST or None)
        if form.is_valid():
            print('The form is valid')
            return redirect('myswapapp/home.html')




def logout(request):
    logout(request)
    return redirect('myswapapp/login.html')



def orderConfirmation(request):
    return render(request,'myswapapp/order_confirmation.html')

myswapapp/templates/myswapapp/add_product_in_basket.html
{% extends 'myswapapp/base.html %}
{% load static %}
{% block title %}Swapping Basket{% endblock title%}
{% block main-content %}


<div class="container my-5">
    <div class="row">
        <h1 class="text-center mb-5">Basket Order Summary</h1>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-body">
                    <h3>Basket</h3>
                    {% for basket in baskets %}
                    <hr>
                    <div class="row">
                        <div class="col-sm-3 text-center align-self-center"><img src="{{ basket.product_image.url }}"
                                alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150">

                        </div>
                        <div class="col-sm-9">
                            <div>
                                <h5>{{basket.product.title}}</h5>
                                <p class="mb-2 text-muted small">{{basket.product.description}}</p>
                                <div class="my-3">
                                    <label for="quantity">Quantity:</label>
                                    <a class="minus-cart btn" pid="{{basket.product}}"></a><i
                                        class="fas fa-minus-square fa-lg"></i></a>
                                    <span id="quantity">{{basket.quantity}}</span>
                                    <a class="plus-cart btn"><i class="fas fa-plus-square fa-lg"></i></a>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <a href="#" class="btn btn-sm btn-secondary mr-3" pid="{{basket.product.id}}">Remove
                                        Product</a>
                                    <p class="mb-0"><span><strong>${{basket.product.price}}</strong></span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="card">
                        <div class="card-body">
                            <h3>Total Dollar Amount for Your Basket is </h3>
                            <ul class="list-group">
                                <li
                                    class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                                    Order Amount<span>((product.price}}</span></li><br>
                                <a href="{% url 'myswapapp:payment' %}"
                                    class="btn btn-outline-warning float-right ml-2">Make Payment</a>
                                <a href="{% url 'myswapapp:home' %}"
                                    class="btn btn-outline-primary float-right">Continue
                                    Swapping</a>
                            </ul>
                        </div>
                    </div>
                </div>


            </div>
        </div>



        {% endblock main-content%}

myswapapp/templates/myswapapp/delete.html
{% extends 'myswapapp/base.html'%}
{% load static %}

{% load crispy_forms_tags %}
{% block title %}Delete Product Form{% endblock title%}

{% block content %}

<p>Are you sure you want to delete product "{{product}}"?</p>

<form action="{% url 'myswapapp:delete_order' product.id %}" method='POST'>
    {% csrf_token %}

    <a href="{% url 'myswapapp:home' %}">Cancel</a>
    <input type="submit" name="Confirm">
</form>
{% endblock content%}

myswapapp/templates/myswapapp/home.html
{% extends 'myswapapp/base.html'%}

{% load static %}

{% block content %}




<style>
    body,
    html {
        margin: 0;
        padding: 0;
        height: 100vh;
        width: 100%;
        background-image: url(/static/images/static/images/pastelornbg.jpg);
        background-position: center;

        background-size: cover;
        position: relative;
    }

    .cards-img {
        justify-content: center;

        padding-top: 30px;


    }

    h2.percentage {
        color: rgb(0, 204, 255);

    }

    .dashboard {
        text-align: center;

    }

    h2.home-title {
        color: royalblue;
    }
</style>






<h2 class=home-title> All Swappers Product List</h2>
</div>
<br>
<br>

{% for product in object_list %}

<section class="header-allpages">
    <div class="dashboard">
        <div class="user">

            <div class="cards-img">
                <div class="card-img">
                    <h3>" {{ product.get_category_display}}"</h3>
                    <img src="{{ product.image.url }}" style='width:20%' alt="">
                </div>


                <div class="card-info">
                    <h5 class="card-title">{{ product.title }}</h5><br>

                    <p class="card-text">{{ product.description}}.</p>

                    <p class="card-text">{{ product.category}}</p>

                </div>


                <h2 class="percentage">Sale 30% off</h2>
                <div class="product-info">
                    <ul class="info">
                        <li><span class="text-uppercase">Price: ${{ product.price|floatformat:2}}</span>
                        </li>
                        <li><span class="text-uppercase">Shipping out of: {{ product.location}}</span>
                        </li>

                    </ul>


                    <a href="{{ product.get_absolute_url }}" class="btn btn-outline-warning" id="clear-item">Swap</a>
                    <button data-product="{{product.id}}" data-action="add"
                        class="btn btn-outline-primary add-btn update-basket">Add

                        to Basket
                    </button><br><br>
                    <hr>
                    {%endfor%}
                </div>
            </div>
        </div>
    </div>
</section>

</div>


{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
    integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
    integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
    crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
<script type="text/javascript">
    // Animation initialization
    new WOW();
</script>

myswapapp/templates/myswapapp/main.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script type="text/javascript" src="{% static 'js/basket.js' %}"></script>
    <script type="text/javascript">
        var user = '{{request.user }}'
    </script>

</head>

<body>


    <div class="container-main">
        <div class="navbar">

            <h3 class="logo">MerrySwap</h3>
            <nav>
                <ul>
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'myswapapp:home' %}" }>Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="{% url 'myswapapp:register' %}">Create an Account</a>
                    </li>
                    <li><a href="#">Testimonies</a>
                    </li>
                </ul>
                {% endif %}
            </nav>

        </div>

    </div>
    </div>


    <div id="content" , name="content" , class="main">
        <div class="row justify-content-center">
            <div class="col-8">
                <h1 class="mt-2">Marisol's MerrySwap App</h1>
                <hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    </div>

    <div class="footer">
        <div class="footer-content">
            <div class="footer-section about"></div>
        </div>

        <div class="footer-bottom">
            &copy; marisol@merryswapp.com | MerrySwap App by Marisol Rodriguez
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script type="text/javascript">
        // Animation initialization
        new WOW();
    </script>
</body>

</html>

myswapapp/templates/myswapapp/swapper_homepage.html
{% extends 'myswapapp/base.html' %}
{% load static %}

{% block content %}

<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>{{ request.user}} Profile:</h5>
            <hr>
            <a class="btn btn-outline-info  btn-sm btn-block" href="">Update User</a>
            <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'myswapapp:create_order' user.id %}">Place
                Order</a>

        </div>
    </div>

    <div class="col-md">
        <div class="card card-body">
            <h5>Contact Information</h5>
            <hr>
            <p>Email: {{user.email}}</p>
            <p>Phone: {{user.phone}}</p>
        </div>
    </div>

    <div class="col-md">
        <div class="card card-body">
            <h5>Total Orders</h5>
            <hr>
            <h1 style="text-align: center;padding: 10px">{{order_count}}</h1>
        </div>
    </div>
</div>


<br>
<div class="row">
    <div class="col">
        <div class="card card-body">

            <form method="get">
                {% csrf_token%}

                <button class="btn btn-primary" type="submit">Search</button>
            </form>

        </div>
    </div>

</div>
<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Note</th>
                    <th>Date Orderd</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>

                {% for order in orders %}

                <tr>
                    <td>{{order.product}}</td>
                    <td>{{order.note}}</td>
                    <td>{{order.date_created}}</td>

                    <td><a class="btn btn-sm btn-info" href="{% url 'myswapapp:update_order' order.id %}">Update</a>
                    </td>

                    <td><a class="btn btn-sm btn-danger" href="{% url 'myswapapp:delete_order' order.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

{% endblock content %}

myswapapp/templates/myswapapp/swapper_profile.html
{% extends 'myswapapp/base.html'%}

{% load static %}
{% load crispy_forms_tags %}
{% block title%}My Profile{% endblock title%}

{% block main-content %}


<div class="container my-5">
    <div class="row">
        <h3>Welcome!! {{ request.user}}</h3>
        <div class="col-sm-2 border-end">
            <ul class="list-unstyled">
                <li class="d-grid"><a href="{% url 'myswapapp:swapper_profile' %}" class="btn">Profile</a></li>
            </ul>
        </div>
        <div class="col-sm 8 offset-sm-1">
            <form action="{% url 'myswapapp:swapper_profile' user.id %}" method='post' novalidate>
                {% csrf_token %}
                {% for fm in form %}
                <div class="form-group col-lg-6 mb-3">
                    {{fm.label_tag }} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
                </div>
                {% endfor %}
                <div class="col-12 mt-3">
                    <button type="submit" class="btn btn-primary mb-3">Submit</button>
                </div>
                <a href="{% url 'myswapapp:swapper_homepage'  %}" class="btn">Profile</a></li>

            </form>
            {% if messages %}
            {% for message in messages %}
            <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock main-content %}